#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page that contains the string
#	listen on port 80
#	Returns a page containing "Ceci n'est pas une page" when queried
#	at the root with a curl GET requeest

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx


# code to create error page and add a redirect for error 404
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
string_for_replacement="server_name _;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/etc\/nginx\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the server
sudo service nginx restart
