#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
# The name of the custom HTTP header must be X-served-By
# The value of the custom HTTP header must be the hostname of the server Nginx is running on

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start


sudo mkdir -p /var/www/html

# change permission to allow us to easily create files in this directory
sudo chmod -R 755 /var/www

# create the index page
echo "Hello World" | sudo tee /var/www/html/index.nginx-ubuntu.html

# create a webpage for error 404
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

new_string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname;\n\trewrite ^\/redirect_me https://www.youtube.com\/watch?v=i7;"
sudo sed -i "s/server_name _;/$new_string_for_replacement/" /etc/nginx/sites-enabled/default

# code to configure redirect for 404 error page
new_string_for_replacement="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation= \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string_for_replacement/" /etc/nginx/sites-enabled/default

# restart the web server after updating the settings
sudo /etc/init.d/nginx restart
