#!/usr/bin/env bash

# Create a script to install and configure HAProxy on Ib-01server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAProxy on my Ib-01 server.

sudo apt-get -y update
apt-get -y install haproxy
sudo apt-get install --no-install-recommends software-properties-common
sudo apt-get-repository ppa:vbernat/haproxy-2.7
sudo apt-get install haproxy=2.7.\*

# edit config file
server_config=\
"
frontend  samy-frontend
	bind *:80
	mode http
	default_backend samy-backend
backend  samy-backend
	balance roundrobin
	server 125552-web-01 100.25.155.74 check
	server 125552-web-02 54.237.114.74 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1 | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
