#!/usr/bin/env bash

# Create a script to install and configure HAProxy on Ib-01server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAProxy on my Ib-01 server.

sudo apt-get -y update
sudo apt-get install haproxy -y


# Configure the server to both frontend and backend
echo "
frontend  http_front
	bind *:80
	mode http
	default_backend http-back
backend  http-back
	balance roundrobin
	server 125552-web-01 34.207.227.51:80 check
	server 125552-web-02 3.90.81.33/80 check
">> /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

sudo sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/haproxy

# Restart Haproxy
sudo service haproxy restart
