#!/usr/bin/env bash
# This script generates a MySQL dump and creates a compressed archive  of it

# Get the password from the command-line argument
MYSQL_PASSWORD="$1"

# Filename formats for the backup
FILE_NAME="$(date +"%s-%m-%Y").tar.gz"

# Dump the MySQL databases and compress then -uroot~= -user=root
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czf "$(date +%d-%m-%Y).tar.gz" "backup.sql"
